version: 2.1

executors:
  sgrep-build:
    environment:
      POETRY_VIRTUALENVS_CREATE: "false"
    docker:
      - image: returntocorp/sgrep-build:2.5

jobs:
  build:
    executor: sgrep-build
    steps:
      - checkout
      - run: cd ~ && git clone  https://github.com/returntocorp/pfff
      - run: poetry install
      - run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env); make all
      - persist_to_workspace:
          root: /home/opam/project
          paths:
            - _build
  test:
    executor: sgrep-build
    steps:
      - checkout
      - attach_workspace:
          at: /home/opam/project
      - run: cd ~ && git clone  https://github.com/returntocorp/pfff # TODO remove and just mount these two lines
      - run: poetry install
      - run: eval $(opam env) && cd ~/pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env); make test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
