version: 2.1
jobs:

  semgrep:
    docker:
      - image: returntocorp/semgrep:develop
    working_directory: /src
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            sudo apk add git
            git submodule init
            git submodule update --remote
      - run: semgrep --config semgrep-core/semgrep.yml --error --strict --exclude ocaml --exclude TODO --exclude _build semgrep-core

workflows:
  version: 2
  semgrep:
    jobs:
      - semgrep
