version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - run: cd ~/opam-repository; git pull
      - run: cd ~/project
      - run: opam update
      - run: opam upgrade -y pfff
      - run: opam show pfff
      - run: eval $(opam env); export PFFF_HOME=/home/opam/project; dune build
      - run: ls -l _build/default/bin/
  test:
    docker:
      - image: returntocorp/sgrep-build:2.1
    steps:
      - checkout
      - run: eval $(opam env); export PFFF_HOME=/home/opam/project; dune runtest
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test