version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: opam update
      - run: opam upgrade -y
      - run: eval $(opam env); export PFFF_HOME=/home/opam/project; dune build
  test:
    docker:
      - image: returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: echo "TODO"
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build