version: 2.1
jobs:
  build:
    docker:
      - image: returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: opam install pfff
      - run: opam install dune
      - run: dune build
  test:
    docker:
      - image: returntocorp/sgrep-build:1.0
    steps:
      - checkout
      - run: echo "TODO!"
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build