name: ci

on: push

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: install system deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: build sgrep-lint
        working-directory: sgrep_lint
        run: make all
