name: ci

on: push

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
      - name: install system deps
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends make
      - uses: actions/setup-python@v1
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: build sgrep-lint
        working-directory: sgrep_lint
        run: make all
  build-sgrep:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:2.7
    steps:
      - run: sudo chmod 777 .
      - uses: actions/checkout@v2
      - run: git submodule init && git submodule update --init --recursive
      - run: eval $(opam env --root /home/opam/.opam --set-root) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam env --root /home/opam/.opam --set-root) && cd sgrep && make all
  test-sgrep:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:2.7
    steps:
      - run: sudo chmod -R 777 . /github
      - uses: actions/checkout@v2
      - run: eval $(opam  env --root /home/opam/.opam --set-root) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - run: eval $(opam  env --root /home/opam/.opam --set-root) && cd sgrep && make && make test && make install
      - run: eval $(opam  env --root /home/opam/.opam --set-root) && cd sgrep_lint && make all && make test
