name: ci

on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    container: returntocorp/sgrep-build:2.7
    steps:
      - name: adjust permissions
        run: sudo chmod -R 777 . /github && export PATH=/github/home/.local/bin:$PATH
      - name: checkout code
        uses: actions/checkout@v2
      - name: install submodules
        run: git submodule update --init --recursive
      - name: install pfff
        run: eval $(opam  env --root /home/opam/.opam --set-root) && cd ./pfff && ./configure && make depend && make && make opt && make install-libs
      - name: install and test sgrep
        run: eval $(opam  env --root /home/opam/.opam --set-root) && cd sgrep && make all && make test && make install
      - name: install and test sgrep-lint
        run: eval $(opam  env --root /home/opam/.opam --set-root) && cd sgrep_lint && make all && make test
