name: tests

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

jobs:
  build-core:
    name: Build and Test semgrep-core
    runs-on: ubuntu-latest
    container: returntocorp/ocaml:alpine
    steps:
      - name: Install pipenv
        run: sudo pip install pipenv
      - name: Pre-checkout fixes
        run: |
          sudo chmod -R 777 /github
          github_cache_dir="/__w"
          sudo mkdir -p "$github_cache_dir"
          sudo chmod -R 777 "$github_cache_dir"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Post-checkout fixes
        run: ./.github/post-checkout
      - name: Build semgrep-core
        run: ./scripts/install-alpine-semgrep-core
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ocaml-build-artifacts
          path: ocaml-build-artifacts.tgz
      - name: Test semgrep-core
        run: |
          eval $(opam env)
          cd semgrep-core
          make test
          make e2etest

  public-repos-test:
    name: run semgrep on public repos
    runs-on: ubuntu-latest
    needs: [build-core]
    strategy:
      matrix:
        python: [3.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ocaml-build-artifacts
      - name: Install artifacts
        run: |
          tar xf ocaml-build-artifacts.tgz
          sudo cp ocaml-build-artifacts/bin/* /usr/bin
      - name: Install semgrep
        run: |
          cd semgrep
          export PATH=/github/home/.local/bin:$PATH
          pip3 install pipenv==2021.5.29
          pipenv install --dev
      - uses: actions/cache@v3
        with:
          path: ~/.cache/semgrep-cache
          key: semgrep-repo-cache-test
      - name: create cache dir if not exists
        run: mkdir -p ~/.cache/semgrep-cache
      - run: touch ~/.cache/semgrep-cache/ok
      - name: Test semgrep SCA
        working-directory: semgrep
        run: |
          export PATH=/github/home/.local/bin:$PATH
          pipenv run semgrep ci --sca
